/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthorizeRouteImport } from './routes/authorize'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PaymentSuccessRouteImport } from './routes/payment/success'
import { Route as ApplicationSignupRouteImport } from './routes/application/signup'
import { Route as ApplicationLoginRouteImport } from './routes/application/login'
import { Route as AdminWebhooksRouteImport } from './routes/admin/webhooks'
import { Route as AdminVisitorsRouteImport } from './routes/admin/visitors'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as AdminRateLimitsRouteImport } from './routes/admin/rate-limits'
import { Route as AdminOverviewRouteImport } from './routes/admin/overview'
import { Route as AdminFeedbackRouteImport } from './routes/admin/feedback'
import { Route as AdminApplicationsRouteImport } from './routes/admin/applications'
import { Route as AdminActivityRouteImport } from './routes/admin/activity'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedBillingRouteImport } from './routes/_protected/billing'
import { Route as ProtectedAccountRouteImport } from './routes/_protected/account'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AdminRolesRoleIdRouteImport } from './routes/admin/roles/$roleId'
import { Route as AdminApplicationsApplicationIdRevocationRouteImport } from './routes/admin/applications_/$applicationId/revocation'
import { Route as AdminApplicationsApplicationIdMembersRouteImport } from './routes/admin/applications_/$applicationId/members'
import { Route as AdminApplicationsApplicationIdClientsRouteImport } from './routes/admin/applications_/$applicationId/clients'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizeRoute = AuthorizeRouteImport.update({
  id: '/authorize',
  path: '/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/_public/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationSignupRoute = ApplicationSignupRouteImport.update({
  id: '/application/signup',
  path: '/application/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationLoginRoute = ApplicationLoginRouteImport.update({
  id: '/application/login',
  path: '/application/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebhooksRoute = AdminWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVisitorsRoute = AdminVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRateLimitsRoute = AdminRateLimitsRouteImport.update({
  id: '/rate-limits',
  path: '/rate-limits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedBillingRoute = ProtectedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAccountRoute = ProtectedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/_auth/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoleIdRoute = AdminRolesRoleIdRouteImport.update({
  id: '/$roleId',
  path: '/$roleId',
  getParentRoute: () => AdminRolesRoute,
} as any)
const AdminApplicationsApplicationIdRevocationRoute =
  AdminApplicationsApplicationIdRevocationRouteImport.update({
    id: '/applications_/$applicationId/revocation',
    path: '/applications/$applicationId/revocation',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminApplicationsApplicationIdMembersRoute =
  AdminApplicationsApplicationIdMembersRouteImport.update({
    id: '/applications_/$applicationId/members',
    path: '/applications/$applicationId/members',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminApplicationsApplicationIdClientsRoute =
  AdminApplicationsApplicationIdClientsRouteImport.update({
    id: '/applications_/$applicationId/clients',
    path: '/applications/$applicationId/clients',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/admin': typeof AdminRouteWithChildren
  '/authorize': typeof AuthorizeRoute
  '/onboarding': typeof OnboardingRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/account': typeof ProtectedAccountRoute
  '/billing': typeof ProtectedBillingRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/settings': typeof ProtectedSettingsRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/rate-limits': typeof AdminRateLimitsRoute
  '/admin/roles': typeof AdminRolesRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/application/login': typeof ApplicationLoginRoute
  '/application/signup': typeof ApplicationSignupRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/roles/$roleId': typeof AdminRolesRoleIdRoute
  '/admin/applications/$applicationId/clients': typeof AdminApplicationsApplicationIdClientsRoute
  '/admin/applications/$applicationId/members': typeof AdminApplicationsApplicationIdMembersRoute
  '/admin/applications/$applicationId/revocation': typeof AdminApplicationsApplicationIdRevocationRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/authorize': typeof AuthorizeRoute
  '/onboarding': typeof OnboardingRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/account': typeof ProtectedAccountRoute
  '/billing': typeof ProtectedBillingRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/settings': typeof ProtectedSettingsRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/rate-limits': typeof AdminRateLimitsRoute
  '/admin/roles': typeof AdminRolesRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/application/login': typeof ApplicationLoginRoute
  '/application/signup': typeof ApplicationSignupRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/admin': typeof AdminIndexRoute
  '/admin/roles/$roleId': typeof AdminRolesRoleIdRoute
  '/admin/applications/$applicationId/clients': typeof AdminApplicationsApplicationIdClientsRoute
  '/admin/applications/$applicationId/members': typeof AdminApplicationsApplicationIdMembersRoute
  '/admin/applications/$applicationId/revocation': typeof AdminApplicationsApplicationIdRevocationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/admin': typeof AdminRouteWithChildren
  '/authorize': typeof AuthorizeRoute
  '/onboarding': typeof OnboardingRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_protected/account': typeof ProtectedAccountRoute
  '/_protected/billing': typeof ProtectedBillingRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/rate-limits': typeof AdminRateLimitsRoute
  '/admin/roles': typeof AdminRolesRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/application/login': typeof ApplicationLoginRoute
  '/application/signup': typeof ApplicationSignupRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/roles/$roleId': typeof AdminRolesRoleIdRoute
  '/admin/applications_/$applicationId/clients': typeof AdminApplicationsApplicationIdClientsRoute
  '/admin/applications_/$applicationId/members': typeof AdminApplicationsApplicationIdMembersRoute
  '/admin/applications_/$applicationId/revocation': typeof AdminApplicationsApplicationIdRevocationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/admin'
    | '/authorize'
    | '/onboarding'
    | '/login'
    | '/signup'
    | '/account'
    | '/billing'
    | '/dashboard'
    | '/settings'
    | '/admin/activity'
    | '/admin/applications'
    | '/admin/feedback'
    | '/admin/overview'
    | '/admin/rate-limits'
    | '/admin/roles'
    | '/admin/users'
    | '/admin/visitors'
    | '/admin/webhooks'
    | '/application/login'
    | '/application/signup'
    | '/payment/success'
    | '/admin/'
    | '/admin/roles/$roleId'
    | '/admin/applications/$applicationId/clients'
    | '/admin/applications/$applicationId/members'
    | '/admin/applications/$applicationId/revocation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/authorize'
    | '/onboarding'
    | '/login'
    | '/signup'
    | '/account'
    | '/billing'
    | '/dashboard'
    | '/settings'
    | '/admin/activity'
    | '/admin/applications'
    | '/admin/feedback'
    | '/admin/overview'
    | '/admin/rate-limits'
    | '/admin/roles'
    | '/admin/users'
    | '/admin/visitors'
    | '/admin/webhooks'
    | '/application/login'
    | '/application/signup'
    | '/payment/success'
    | '/admin'
    | '/admin/roles/$roleId'
    | '/admin/applications/$applicationId/clients'
    | '/admin/applications/$applicationId/members'
    | '/admin/applications/$applicationId/revocation'
  id:
    | '__root__'
    | '/_protected'
    | '/accept-invitation'
    | '/admin'
    | '/authorize'
    | '/onboarding'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_protected/account'
    | '/_protected/billing'
    | '/_protected/dashboard'
    | '/_protected/settings'
    | '/admin/activity'
    | '/admin/applications'
    | '/admin/feedback'
    | '/admin/overview'
    | '/admin/rate-limits'
    | '/admin/roles'
    | '/admin/users'
    | '/admin/visitors'
    | '/admin/webhooks'
    | '/application/login'
    | '/application/signup'
    | '/payment/success'
    | '/_public/'
    | '/admin/'
    | '/admin/roles/$roleId'
    | '/admin/applications_/$applicationId/clients'
    | '/admin/applications_/$applicationId/members'
    | '/admin/applications_/$applicationId/revocation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthorizeRoute: typeof AuthorizeRoute
  OnboardingRoute: typeof OnboardingRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  ApplicationLoginRoute: typeof ApplicationLoginRoute
  ApplicationSignupRoute: typeof ApplicationSignupRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorize': {
      id: '/authorize'
      path: '/authorize'
      fullPath: '/authorize'
      preLoaderRoute: typeof AuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application/signup': {
      id: '/application/signup'
      path: '/application/signup'
      fullPath: '/application/signup'
      preLoaderRoute: typeof ApplicationSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application/login': {
      id: '/application/login'
      path: '/application/login'
      fullPath: '/application/login'
      preLoaderRoute: typeof ApplicationLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/webhooks': {
      id: '/admin/webhooks'
      path: '/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AdminWebhooksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/visitors': {
      id: '/admin/visitors'
      path: '/visitors'
      fullPath: '/admin/visitors'
      preLoaderRoute: typeof AdminVisitorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rate-limits': {
      id: '/admin/rate-limits'
      path: '/rate-limits'
      fullPath: '/admin/rate-limits'
      preLoaderRoute: typeof AdminRateLimitsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/overview': {
      id: '/admin/overview'
      path: '/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/billing': {
      id: '/_protected/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof ProtectedBillingRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/account': {
      id: '/_protected/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ProtectedAccountRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles/$roleId': {
      id: '/admin/roles/$roleId'
      path: '/$roleId'
      fullPath: '/admin/roles/$roleId'
      preLoaderRoute: typeof AdminRolesRoleIdRouteImport
      parentRoute: typeof AdminRolesRoute
    }
    '/admin/applications_/$applicationId/revocation': {
      id: '/admin/applications_/$applicationId/revocation'
      path: '/applications/$applicationId/revocation'
      fullPath: '/admin/applications/$applicationId/revocation'
      preLoaderRoute: typeof AdminApplicationsApplicationIdRevocationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications_/$applicationId/members': {
      id: '/admin/applications_/$applicationId/members'
      path: '/applications/$applicationId/members'
      fullPath: '/admin/applications/$applicationId/members'
      preLoaderRoute: typeof AdminApplicationsApplicationIdMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications_/$applicationId/clients': {
      id: '/admin/applications_/$applicationId/clients'
      path: '/applications/$applicationId/clients'
      fullPath: '/admin/applications/$applicationId/clients'
      preLoaderRoute: typeof AdminApplicationsApplicationIdClientsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedAccountRoute: typeof ProtectedAccountRoute
  ProtectedBillingRoute: typeof ProtectedBillingRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAccountRoute: ProtectedAccountRoute,
  ProtectedBillingRoute: ProtectedBillingRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface AdminRolesRouteChildren {
  AdminRolesRoleIdRoute: typeof AdminRolesRoleIdRoute
}

const AdminRolesRouteChildren: AdminRolesRouteChildren = {
  AdminRolesRoleIdRoute: AdminRolesRoleIdRoute,
}

const AdminRolesRouteWithChildren = AdminRolesRoute._addFileChildren(
  AdminRolesRouteChildren,
)

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminOverviewRoute: typeof AdminOverviewRoute
  AdminRateLimitsRoute: typeof AdminRateLimitsRoute
  AdminRolesRoute: typeof AdminRolesRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVisitorsRoute: typeof AdminVisitorsRoute
  AdminWebhooksRoute: typeof AdminWebhooksRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminApplicationsApplicationIdClientsRoute: typeof AdminApplicationsApplicationIdClientsRoute
  AdminApplicationsApplicationIdMembersRoute: typeof AdminApplicationsApplicationIdMembersRoute
  AdminApplicationsApplicationIdRevocationRoute: typeof AdminApplicationsApplicationIdRevocationRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminOverviewRoute: AdminOverviewRoute,
  AdminRateLimitsRoute: AdminRateLimitsRoute,
  AdminRolesRoute: AdminRolesRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AdminVisitorsRoute: AdminVisitorsRoute,
  AdminWebhooksRoute: AdminWebhooksRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminApplicationsApplicationIdClientsRoute:
    AdminApplicationsApplicationIdClientsRoute,
  AdminApplicationsApplicationIdMembersRoute:
    AdminApplicationsApplicationIdMembersRoute,
  AdminApplicationsApplicationIdRevocationRoute:
    AdminApplicationsApplicationIdRevocationRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  AcceptInvitationRoute: AcceptInvitationRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthorizeRoute: AuthorizeRoute,
  OnboardingRoute: OnboardingRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  ApplicationLoginRoute: ApplicationLoginRoute,
  ApplicationSignupRoute: ApplicationSignupRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  PublicIndexRoute: PublicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
