/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StandaloneRouteImport } from './routes/standalone'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BetterAuthRouteImport } from './routes/better-auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StandaloneDashboardRouteImport } from './routes/standalone_.dashboard'
import { Route as BetterAuthDashboardRouteImport } from './routes/better-auth_.dashboard'

const StandaloneRoute = StandaloneRouteImport.update({
  id: '/standalone',
  path: '/standalone',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BetterAuthRoute = BetterAuthRouteImport.update({
  id: '/better-auth',
  path: '/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StandaloneDashboardRoute = StandaloneDashboardRouteImport.update({
  id: '/standalone_/dashboard',
  path: '/standalone/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BetterAuthDashboardRoute = BetterAuthDashboardRouteImport.update({
  id: '/better-auth_/dashboard',
  path: '/better-auth/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/better-auth': typeof BetterAuthRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/standalone': typeof StandaloneRoute
  '/better-auth/dashboard': typeof BetterAuthDashboardRoute
  '/standalone/dashboard': typeof StandaloneDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/better-auth': typeof BetterAuthRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/standalone': typeof StandaloneRoute
  '/better-auth/dashboard': typeof BetterAuthDashboardRoute
  '/standalone/dashboard': typeof StandaloneDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/better-auth': typeof BetterAuthRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/standalone': typeof StandaloneRoute
  '/better-auth_/dashboard': typeof BetterAuthDashboardRoute
  '/standalone_/dashboard': typeof StandaloneDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/better-auth'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/standalone'
    | '/better-auth/dashboard'
    | '/standalone/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/better-auth'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/standalone'
    | '/better-auth/dashboard'
    | '/standalone/dashboard'
  id:
    | '__root__'
    | '/'
    | '/better-auth'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/standalone'
    | '/better-auth_/dashboard'
    | '/standalone_/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BetterAuthRoute: typeof BetterAuthRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  StandaloneRoute: typeof StandaloneRoute
  BetterAuthDashboardRoute: typeof BetterAuthDashboardRoute
  StandaloneDashboardRoute: typeof StandaloneDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/standalone': {
      id: '/standalone'
      path: '/standalone'
      fullPath: '/standalone'
      preLoaderRoute: typeof StandaloneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/better-auth': {
      id: '/better-auth'
      path: '/better-auth'
      fullPath: '/better-auth'
      preLoaderRoute: typeof BetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standalone_/dashboard': {
      id: '/standalone_/dashboard'
      path: '/standalone/dashboard'
      fullPath: '/standalone/dashboard'
      preLoaderRoute: typeof StandaloneDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/better-auth_/dashboard': {
      id: '/better-auth_/dashboard'
      path: '/better-auth/dashboard'
      fullPath: '/better-auth/dashboard'
      preLoaderRoute: typeof BetterAuthDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BetterAuthRoute: BetterAuthRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  StandaloneRoute: StandaloneRoute,
  BetterAuthDashboardRoute: BetterAuthDashboardRoute,
  StandaloneDashboardRoute: StandaloneDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
