/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StandaloneRouteImport } from './routes/standalone'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BetterAuthRouteImport } from './routes/better-auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StandaloneIndexRouteImport } from './routes/standalone/index'
import { Route as BetterAuthIndexRouteImport } from './routes/better-auth/index'
import { Route as StandaloneDashboardRouteImport } from './routes/standalone/dashboard'
import { Route as BetterAuthDashboardRouteImport } from './routes/better-auth/dashboard'

const StandaloneRoute = StandaloneRouteImport.update({
  id: '/standalone',
  path: '/standalone',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BetterAuthRoute = BetterAuthRouteImport.update({
  id: '/better-auth',
  path: '/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StandaloneIndexRoute = StandaloneIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StandaloneRoute,
} as any)
const BetterAuthIndexRoute = BetterAuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BetterAuthRoute,
} as any)
const StandaloneDashboardRoute = StandaloneDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StandaloneRoute,
} as any)
const BetterAuthDashboardRoute = BetterAuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => BetterAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/better-auth': typeof BetterAuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/standalone': typeof StandaloneRouteWithChildren
  '/better-auth/dashboard': typeof BetterAuthDashboardRoute
  '/standalone/dashboard': typeof StandaloneDashboardRoute
  '/better-auth/': typeof BetterAuthIndexRoute
  '/standalone/': typeof StandaloneIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/better-auth/dashboard': typeof BetterAuthDashboardRoute
  '/standalone/dashboard': typeof StandaloneDashboardRoute
  '/better-auth': typeof BetterAuthIndexRoute
  '/standalone': typeof StandaloneIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/better-auth': typeof BetterAuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/standalone': typeof StandaloneRouteWithChildren
  '/better-auth/dashboard': typeof BetterAuthDashboardRoute
  '/standalone/dashboard': typeof StandaloneDashboardRoute
  '/better-auth/': typeof BetterAuthIndexRoute
  '/standalone/': typeof StandaloneIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/better-auth'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/standalone'
    | '/better-auth/dashboard'
    | '/standalone/dashboard'
    | '/better-auth/'
    | '/standalone/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/better-auth/dashboard'
    | '/standalone/dashboard'
    | '/better-auth'
    | '/standalone'
  id:
    | '__root__'
    | '/'
    | '/better-auth'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/standalone'
    | '/better-auth/dashboard'
    | '/standalone/dashboard'
    | '/better-auth/'
    | '/standalone/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BetterAuthRoute: typeof BetterAuthRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  StandaloneRoute: typeof StandaloneRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/standalone': {
      id: '/standalone'
      path: '/standalone'
      fullPath: '/standalone'
      preLoaderRoute: typeof StandaloneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/better-auth': {
      id: '/better-auth'
      path: '/better-auth'
      fullPath: '/better-auth'
      preLoaderRoute: typeof BetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standalone/': {
      id: '/standalone/'
      path: '/'
      fullPath: '/standalone/'
      preLoaderRoute: typeof StandaloneIndexRouteImport
      parentRoute: typeof StandaloneRoute
    }
    '/better-auth/': {
      id: '/better-auth/'
      path: '/'
      fullPath: '/better-auth/'
      preLoaderRoute: typeof BetterAuthIndexRouteImport
      parentRoute: typeof BetterAuthRoute
    }
    '/standalone/dashboard': {
      id: '/standalone/dashboard'
      path: '/dashboard'
      fullPath: '/standalone/dashboard'
      preLoaderRoute: typeof StandaloneDashboardRouteImport
      parentRoute: typeof StandaloneRoute
    }
    '/better-auth/dashboard': {
      id: '/better-auth/dashboard'
      path: '/dashboard'
      fullPath: '/better-auth/dashboard'
      preLoaderRoute: typeof BetterAuthDashboardRouteImport
      parentRoute: typeof BetterAuthRoute
    }
  }
}

interface BetterAuthRouteChildren {
  BetterAuthDashboardRoute: typeof BetterAuthDashboardRoute
  BetterAuthIndexRoute: typeof BetterAuthIndexRoute
}

const BetterAuthRouteChildren: BetterAuthRouteChildren = {
  BetterAuthDashboardRoute: BetterAuthDashboardRoute,
  BetterAuthIndexRoute: BetterAuthIndexRoute,
}

const BetterAuthRouteWithChildren = BetterAuthRoute._addFileChildren(
  BetterAuthRouteChildren,
)

interface StandaloneRouteChildren {
  StandaloneDashboardRoute: typeof StandaloneDashboardRoute
  StandaloneIndexRoute: typeof StandaloneIndexRoute
}

const StandaloneRouteChildren: StandaloneRouteChildren = {
  StandaloneDashboardRoute: StandaloneDashboardRoute,
  StandaloneIndexRoute: StandaloneIndexRoute,
}

const StandaloneRouteWithChildren = StandaloneRoute._addFileChildren(
  StandaloneRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BetterAuthRoute: BetterAuthRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  StandaloneRoute: StandaloneRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
